name: dotagiftx_mobile
description: "mobile platform for https://dotagiftx.com"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  copy_with_extension: ^6.0.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_analytics: ^10.10.5
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  firebase_performance: ^0.9.4+7
  firebase_remote_config: ^4.4.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  retrofit: ^4.5.0
  rxdart: ^0.28.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.5.4
  copy_with_extension_gen: ^6.0.1
  fake_async: ^1.3.2
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  retrofit_generator: ^9.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/treasures/

flutter_gen:
  output: lib/presentation/shared/assets/
  line_length: 120
  fonts:
    enabled: false

flutter_intl:
  enabled: true
  class_name: I18n
  arb_dir: lib/presentation/shared/localization
  output_dir: lib/presentation/shared/localization/generated
