name: 'Setup Flutter Environment'
description: 'Sets up Flutter, dependencies, and runs code generation'

runs:
  using: 'composite'
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get
      shell: bash

    - name: Generate internationalization code
      run: flutter pub run intl_utils:generate
      shell: bash

    - name: Code generation
      run: dart run build_runner build --delete-conflicting-outputs
      shell: bash 