name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Generate internationalization code
      run: flutter pub run intl_utils:generate

    - name: Code generation
      run: dart run build_runner build --delete-conflicting-outputs

    - name: Code format validation
      run: flutter analyze .

    - name: Run tests with coverage
      run: flutter test --coverage

    - name: Install lcov
      run: sudo apt-get update && sudo apt-get install -y lcov

    - name: Process coverage data
      run: |
        lcov --extract coverage/lcov.info 'lib/presentation/**/viewmodels/*' 'lib/domain/usecases/*' -o coverage/lcov.info
        genhtml coverage/lcov.info -o coverage/html

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html-report
        path: coverage/html

    - name: Check coverage threshold
      run: |
        COVERAGE=$(lcov --summary coverage/lcov.info | grep -E "lines\.*:" | sed 's/.*lines.*: \([0-9.]*\)%.*/\1/')
        echo "Coverage: ${COVERAGE}%"
        # Convert to integer by multiplying by 100 and removing decimal point
        COVERAGE_SCALED=$(echo "$COVERAGE * 100" | awk '{printf "%.0f", $1}')
        THRESHOLD_SCALED=8000  # 80.00 * 100
        if [ "$COVERAGE_SCALED" -lt "$THRESHOLD_SCALED" ]; then
          echo "❌ Coverage ${COVERAGE}% is below minimum threshold of 80%"
          exit 1
        else
          echo "✅ Coverage ${COVERAGE}% meets minimum threshold of 80%"
        fi

    - name: Coverage summary
      run: |
        echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
        echo "Coverage report has been generated and uploaded as an artifact." >> $GITHUB_STEP_SUMMARY
        lcov --summary coverage/lcov.info >> $GITHUB_STEP_SUMMARY 